# Apply Bao (2013) to a 2026 VIX option chain.
#
#   1. Paper procedure (ch. 7): per maturity, all parameters free, spot VIX as
#      underlying, MMLSE loss (α = 8) on mid quotes with positive bid and OI.
#   2. Out-of-sample: same fit on every other strike, errors on the rest.
#   3. Futures consistency: model future implied by the ch.-7 fit vs the
#      market future implied by put-call parity.
#   4. Identification: MRLR loss as a function of a fixed κ.
#   5. Term structure: one set of dynamics parameters for all four maturities,
#      θ anchored per maturity to the market future (the paper's own two-stage
#      strategy of Theorems 3.3/4.4/5.4).
#
# Usage: julia -t auto --project=. scripts/calibrate_2026.jl [snapshot.json]
#        (default: the newest file in data/cboe/)

using VIXModels, DataFrames, Dates, Printf, Statistics, Optim

const ROOT = normpath(joinpath(@__DIR__, "..", ".."))
snapshot = length(ARGS) > 0 ? ARGS[1] :
    last(sort(filter(endswith(".json"), readdir(joinpath(ROOT, "data", "cboe"); join = true))))
q, spot, valuation = parse_cboe(read(snapshot, String))
expiries = sort(unique(q.expiry[q.root.=="VIX"]))[1:4]      # four liquid monthlies, as in the paper
slices, r = build_slices(q, valuation; expiries)
const MODELS = (MRLR, MRLRJ, MRLRSV)
nstarts(M) = M === MRLRSV ? 6 : 10
tag = Dates.format(Date(valuation), "yyyy-mm-dd")

io = IOBuffer()
pct(x) = @sprintf("%.2f%%", 100x)
f3(x) = @sprintf("%.3f", x)
fmtp(m) = join((@sprintf("%s=%.3g", n, v) for (n, v) in zip(paramnames(m), params(m))), ", ")

println(io, "# Bao (2013) applied to the VIX option chain of $tag\n")
println(io, "Generated by `julia_impl/scripts/calibrate_2026.jl` from `",
        relpath(snapshot, ROOT), "`.\n")
@printf(io, "Spot VIX %.2f at %s ET. Parity-implied rate r = %.2f%%.\n\n", spot, valuation, 100r)
println(io, "| Expiry | τ (yrs) | Parity VIX future | Effective quotes | Avg OI |")
println(io, "|---|---|---|---|---|")
for s in slices
    @printf(io, "| %s | %.4f | %.3f | %d | %d |\n", s.expiry, s.τ, s.F, length(s.K), round(Int, mean(s.oi)))
end

# ---------------------------------------------------------------------------
# 1 + 3. Paper procedure
# ---------------------------------------------------------------------------
# Every (model, maturity) fit is independent: run them on separate threads
# (start julia with -t auto).
function progress(msg)
    println(stderr, Dates.format(now(), "HH:MM:SS"), "  ", msg)
    flush(stderr)
end
function threaded(f, jobs)
    tasks = [Threads.@spawn f(j) for j in jobs]
    return fetch.(tasks)
end

jobs = [(M, i) for M in MODELS for i in eachindex(slices)]
results = threaded(jobs) do (M, i)
    s = slices[i]
    t = @elapsed (ms, _) = calibrate(M, spot, [s]; nstarts = nstarts(M))
    m = ms[1]
    p = vix_calls(m, spot, s.τ, s.K; D = s.D)
    st = fit_stats(p, s)
    progress("paper fit $(modelname(M)) $(s.expiry): PE $(pct(st.PE)) ($(round(Int, t)) s)")
    (model = m, stats = st, F = vix_future(m, spot, s.τ), prices = p)
end
fits = Dict(M => [results[findfirst(==((M, i)), jobs)] for i in eachindex(slices)] for M in MODELS)
curves = DataFrame()
for M in MODELS, (i, s) in enumerate(slices)
    append!(curves, DataFrame(model = modelname(M), expiry = s.expiry, strike = s.K,
                              bid = s.bid, ask = s.ask, mid = mid(s), fit = fits[M][i].prices))
end

println(io, "\n## 1. Paper procedure (chapter 7)\n")
println(io, "Percentage error (PE), mean absolute error (MAE) and share of model prices ",
        "inside the bid-ask band. Paper values (Sep-2011) for comparison: PE 4.7–6.9% ",
        "(MRLR), 3.1–5.2% (MRLRJ), 3.0–5.1% (MRLRSV).\n")
println(io, "| Expiry | MRLR PE | MRLRJ PE | MRLRSV PE | MRLR MAE | MRLRJ MAE | MRLRSV MAE | MRLR in-band | MRLRJ in-band | MRLRSV in-band |")
println(io, "|---|---|---|---|---|---|---|---|---|---|")
for (i, s) in enumerate(slices)
    st = [fits[M][i].stats for M in MODELS]
    println(io, "| ", s.expiry, " | ", join(pct.(getfield.(st, :PE)), " | "), " | ",
            join(f3.(getfield.(st, :MAE)), " | "), " | ", join(pct.(getfield.(st, :inband)), " | "), " |")
end
println(io, "\nCalibrated parameters:\n")
for M in MODELS, (i, s) in enumerate(slices)
    println(io, "- ", modelname(M), " ", s.expiry, ": ", fmtp(fits[M][i].model))
end

println(io, "\n## 2. Futures consistency of the chapter-7 fits\n")
println(io, "The chapter-7 procedure never looks at the VIX future. Model future ",
        "(ψ(−i) with spot VIX as input) vs the market future implied by put-call parity:\n")
println(io, "| Expiry | Market | MRLR | MRLRJ | MRLRSV |\n|---|---|---|---|---|")
for (i, s) in enumerate(slices)
    println(io, "| ", s.expiry, " | ", f3(s.F), " | ",
            join((@sprintf("%.3f (%+.1f%%)", fits[M][i].F, 100(fits[M][i].F / s.F - 1)) for M in MODELS), " | "), " |")
end

# ---------------------------------------------------------------------------
# 2. Out-of-sample strikes
# ---------------------------------------------------------------------------
println(io, "\n## 3. Out-of-sample strikes\n")
println(io, "Fit on strikes with odd rank, evaluate on the others (paper procedure otherwise unchanged).\n")
println(io, "| Expiry | Model | in-sample PE | out-of-sample PE | out-of-sample MAE | out-of-sample in-band |")
println(io, "|---|---|---|---|---|---|")
oos_jobs = [(i, M) for i in eachindex(slices) for M in MODELS]
oos = threaded(oos_jobs) do (i, M)
    s = slices[i]
    tr, te = subslice(s, 1:2:length(s.K)), subslice(s, 2:2:length(s.K))
    (ms, _) = calibrate(M, spot, [tr]; nstarts = nstarts(M))
    a = fit_stats(vix_calls(ms[1], spot, tr.τ, tr.K; D = tr.D), tr)
    b = fit_stats(vix_calls(ms[1], spot, te.τ, te.K; D = te.D), te)
    progress("out-of-sample $(modelname(M)) $(s.expiry): PE $(pct(b.PE))")
    (a, b)
end
for ((i, M), (a, b)) in zip(oos_jobs, oos)
    println(io, "| ", slices[i].expiry, " | ", modelname(M), " | ", pct(a.PE), " | ", pct(b.PE), " | ",
            f3(b.MAE), " | ", pct(b.inband), " |")
end

# ---------------------------------------------------------------------------
# 4. Identification of κ in MRLR
# ---------------------------------------------------------------------------
println(io, "\n## 4. Is κ identified from one maturity?\n")
println(io, "MRLR with κ held fixed, θ and σ refitted (first expiry). Under MRLR one ",
        "maturity only pins down the mean and variance of ln VIX_T, so the loss should not depend on κ.\n")
println(io, "| fixed κ | best loss | θ | σ |\n|---|---|---|---|")
let s = slices[1], c = mid(slices[1])
    for κ in (0.5, 2.0, 8.0, 32.0)
        obj(x) = mmlse(vix_calls(MRLR(κ, x[1], exp(x[2])), spot, s.τ, s.K; D = s.D), c)
        res = optimize(obj, [log(s.F), 0.0], NelderMead(), Optim.Options(iterations = 5000))
        x = Optim.minimizer(res)
        println(io, "| ", κ, " | ", @sprintf("%.6f", Optim.minimum(res)), " | ", f3(x[1]), " | ", f3(exp(x[2])), " |")
    end
end

# ---------------------------------------------------------------------------
# 5. Joint term-structure fit
# ---------------------------------------------------------------------------
println(io, "\n## 5. One model for the whole term structure\n")
println(io, "Dynamics parameters shared by all four maturities; θ set per maturity so the ",
        "model matches the market future exactly.\n")
println(io, "| Model | ", join(string.(expiries), " PE | "), " PE | mean in-band | parameters |")
println(io, "|---|", repeat("---|", length(expiries) + 2))
joint = threaded(collect(MODELS)) do M
    t = @elapsed (ms, _) = calibrate(M, spot, slices; anchored = true, nstarts = nstarts(M))
    progress("joint fit $(modelname(M)) ($(round(Int, t)) s)")
    ms
end
for (M, ms) in zip(MODELS, joint)
    st = [fit_stats(vix_calls(m, spot, s.τ, s.K; D = s.D), s) for (m, s) in zip(ms, slices)]
    println(io, "| ", modelname(M), " | ", join(pct.(getfield.(st, :PE)), " | "), " | ",
            pct(mean(getfield.(st, :inband))), " | ", fmtp(ms[1]), " (θ per maturity: ",
            join((@sprintf("%.3f", m.θ) for m in ms), ", "), ") |")
end

report = String(take!(io))
mkpath(joinpath(ROOT, "results"))
write(joinpath(ROOT, "results", "calibration_$tag.md"), report)
open(joinpath(ROOT, "results", "calibration_$(tag)_curves.csv"), "w") do f
    println(f, join(names(curves), ","))
    for row in eachrow(curves)
        println(f, join(row, ","))
    end
end
print(report)
