# Consistency check against the published calibration of Bao (2013), ch. 7.
#
# The 2011 CBOE quotes used in the paper are not public, so the fitting errors
# of Tables 7.2/7.3 cannot be recomputed. What *can* be checked is whether the
# published parameter tables (7.4 MRLR, 7.5 MRLRJ, 7.6 MRLRSV), priced with
# this implementation, behave like three fits to the same market:
#   * MRLRJ and MRLRSV prices should nearly coincide (the paper reports MAEs of
#     ~0.12-0.21 vs market for both, so they can differ by at most ~2x that),
#   * MRLR should differ more (paper MAE 0.33-0.43),
#   * against the model future, MRLR must be flat and MRLRJ/MRLRSV upward
#     sloping (Figure 7.3), at vol levels similar to the figure's axes.
#
# Usage: julia --project=. scripts/reproduce_paper.jl

using VIXModels, Dates, Printf, Statistics

const V = 42.3                                    # spot VIX, 26-Sep-2011 10:01 ET
const valuation = DateTime(2011, 9, 26, 10, 1)
const expiries = [Date(2011, 10, 18), Date(2011, 11, 15), Date(2011, 12, 20), Date(2012, 1, 17)]
const K = collect(20.0:5.0:90.0)

const tables = Dict(
    "MRLR" => [MRLR(11.05, 3.38, 1.97), MRLR(11.43, 3.39, 2.07),
               MRLR(9.88, 3.29, 2.18), MRLR(12.58, 3.34, 2.48)],
    "MRLRJ" => [MRLRJ(29.84, 3.00, 1.46, 169.45, 9.94), MRLRJ(28.78, 3.00, 2.44, 138.89, 10.09),
                MRLRJ(29.55, 3.00, 2.97, 84.76, 7.74), MRLRJ(21.86, 3.00, 2.31, 59.53, 6.71)],
    "MRLRSV" => [MRLRSV(4.27, 3.14, 1.00, 1.68, 1.11, 1.98, 1.81),
                 MRLRSV(5.10, 3.25, 1.00, 1.89, 1.12, 0.71, 2.00),
                 MRLRSV(3.48, 3.11, 1.00, 1.67, 1.08, 0.57, 1.63),
                 MRLRSV(3.53, 3.26, 1.00, 1.56, 1.03, 0.65, 1.37)])
const paper_mae = Dict("MRLR" => [0.4334, 0.3287, 0.3566, 0.3569],
                       "MRLRJ" => [0.1162, 0.1843, 0.2097, 0.1322],
                       "MRLRSV" => [0.1214, 0.1752, 0.1995, 0.1286])
# Approximate y-axis ranges of Figure 7.3 (implied vol vs VIX future)
const fig73 = ["1.2 – 1.8", "1.05 – 1.3", "0.75 – 1.2", "0.7 – 1.1"]

io = IOBuffer()
println(io, "# Consistency check of Bao (2013) Tables 7.4–7.6\n")
println(io, "Generated by `julia_impl/scripts/reproduce_paper.jl`. Spot VIX 42.3, ",
        "valuation 26-Sep-2011 10:01 ET, strikes 20–90, r = 0.\n")

println(io, "## Model VIX futures implied by the published parameters\n")
println(io, "| Expiry | MRLR | MRLRJ | MRLRSV |\n|---|---|---|---|")
for (i, e) in enumerate(expiries)
    τ = year_fraction(valuation, e)
    @printf(io, "| %s | %.2f | %.2f | %.2f |\n", e,
            (vix_future(tables[m][i], V, τ) for m in ("MRLR", "MRLRJ", "MRLRSV"))...)
end

println(io, "\n## Do the three parameter sets describe the same market?\n")
println(io, "Mean absolute price difference between models over strikes 20–90, next to ",
        "the paper's reported MAE vs market (Table 7.3). If the implementation matches ",
        "the paper's conventions, |MRLRJ − MRLRSV| must be at most about ",
        "MAE(J) + MAE(SV).\n")
println(io, "| Expiry | \\|MRLRJ − MRLRSV\\| | paper MAE(J)+MAE(SV) | \\|MRLR − MRLRJ\\| | paper MAE(MRLR) |")
println(io, "|---|---|---|---|---|")
for (i, e) in enumerate(expiries)
    τ = year_fraction(valuation, e)
    p = Dict(m => vix_calls(tables[m][i], V, τ, K) for m in keys(tables))
    @printf(io, "| %s | %.3f | %.3f | %.3f | %.3f |\n", e,
            mean(abs.(p["MRLRJ"] .- p["MRLRSV"])), paper_mae["MRLRJ"][i] + paper_mae["MRLRSV"][i],
            mean(abs.(p["MRLR"] .- p["MRLRJ"])), paper_mae["MRLR"][i])
end

println(io, "\n## Implied volatility skew against the model future (Figure 7.3)\n")
println(io, "Black implied vol at K = 40 / 60 / 80 using each model's own future.\n")
println(io, "| Expiry | MRLR | MRLRJ | MRLRSV | Figure 7.3 axis |\n|---|---|---|---|---|")
for (i, e) in enumerate(expiries)
    τ = year_fraction(valuation, e)
    cells = String[]
    for m in ("MRLR", "MRLRJ", "MRLRSV")
        mdl = tables[m][i]
        F = vix_future(mdl, V, τ)
        ivs = [black_iv(vix_call(mdl, V, τ, k), F, k, τ) for k in (40.0, 60.0, 80.0)]
        push!(cells, join((@sprintf("%.2f", x) for x in ivs), " / "))
    end
    @printf(io, "| %s | %s | %s | %s | %s |\n", e, cells..., fig73[i])
end

report = String(take!(io))
mkpath(joinpath(@__DIR__, "..", "..", "results"))
write(joinpath(@__DIR__, "..", "..", "results", "paper_2011_check.md"), report)
print(report)
